feat: Add support for PHP 8
Roave/DoctrineSimpleCache pull request #37
Opened 2021-01-02 21:40 UTC by bednic

Enable use this library in project with PHP 8 platform

2021-01-02 22:30 UTC, Ocramius commented on .travis.yml
>    - 7.2
Let's drop 7.2 and 7.3 :)

2021-01-03 10:48 UTC, bednic commented
What I'm doing wrong? I didn't configs for infection, but they are still failing.

2021-01-11 15:40 UTC, asgrim commented
Hmm, I think it's something to do with new configuration needed for Xdebug 3, although I haven't personally checked it yet

2021-01-11 18:27 UTC, Ocramius commented
Since travis-ci is dead-dead-dead, I suggest copying over all the CI setup of https://github.com/Roave/BetterReflection/tree/aac4cbae45c6b201887ceba1425837f784c5a5dd/.github/workflows (where applicable), which should be capable of running infection with pcov by default.

2021-01-12 20:52 UTC, bednic commented
Well, it's good idea and I can do it in this PR. But need from @Ocramius to know which workflow to copy. Because, for example, benchmark workflow cannot be copied, there is no benchmark tests. And I can copy even StanPHP, but it will probably create even more problems. This should be an easy change 😄!

2021-01-13 07:40 UTC, asgrim commented
@bednic we'd only need the existing workflows ported over, using our other repos as references to guide things (although they're not always perfect either heh) 😁

2021-01-13 08:27 UTC, Ocramius commented
From what I can see, only phpunit and mutation testing are supported here.

I'd also copy over the release automation stuff, since it's really making everything much simpler to maintain.

That means 3 files :-)

2021-01-16 21:27 UTC, bednic commented
Should be ready. Workflow is green in my fork, so I expect after merge, it will be green here too.

2021-01-17 06:12 UTC, asgrim requested changes
Need to remove the Scrutinizer integration from our end, will do it when I'm at a pooter. Also not sure why GH checks didn't run, any ideas @Ocramius ?

2021-01-17 06:12 UTC, asgrim commented on composer.json
> +        "php": "^7.4 || ^8.0",
We probably don't want to support PHP 8.* Yet, I'd suggest `^7.4 || 8.0.*`

2021-01-17 06:12 UTC, asgrim commented on .github/workflows/release-on-milestone-closed-triggering-release-event.yml
> +      - name: "Bump Changelog Version On Originating Release Branch"
We could remove this changelog step since we don't actually maintain a changelog here

2021-01-17 14:44 UTC, Ocramius commented
> Also not sure why GH checks didn't run, any ideas @Ocramius ?

They don't run because github actions only run based on `master` definitions at the moment: this is because github actions can access repository secrets, which shouldn't be exfiltrated in PRs.

They did run under https://github.com/bednic/DoctrineSimpleCache/actions

2021-01-17 14:44 UTC, Ocramius approved these changes
:ship:

2021-01-17 14:45 UTC, merged

2021-01-17 14:45 UTC, Ocramius commented
Thanks @bednic!