php 8.3 support
Roave/DoctrineSimpleCache pull request #61
Opened 2024-02-05 11:45 UTC by krumynin

2024-02-05 12:35 UTC, Ocramius requested changes
See also #59

2024-02-05 12:35 UTC, Ocramius commented on composer.json
> +        "php": "~8.0.0 || ~8.1.0 || ~8.2.0 || ~8.3.0",
`composer.lock` hash needs appropriate update too.

2024-02-05 12:44 UTC, Ocramius commented on composer.lock
> +            "version": "3.1.1",
Uhh, upgrading everything may cause quite a mess. See #57

2024-02-05 12:51 UTC, krumynin commented on composer.lock
> +            "version": "3.1.1",
done, updated only php

2024-02-06 10:26 UTC, krumynin commented
hello, can you merge it please and make a new release ?)

2024-02-06 18:34 UTC, Ocramius approved these changes
Yup, thanks @krumynin!

2024-02-06 18:34 UTC, merged